// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7r-TzQm2J4-EvI-H6jphfncVx9uHBrsQ',
    appId: '1:352111075138:web:8212a46ed31426658c32db',
    messagingSenderId: '352111075138',
    projectId: 'myprotfolio-a0b51',
    authDomain: 'myprotfolio-a0b51.firebaseapp.com',
    storageBucket: 'myprotfolio-a0b51.firebasestorage.app',
    measurementId: 'G-R7CYHYP7GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZde0dFPtnWo7rrB-FasrfMADRBCjg3Os',
    appId: '1:352111075138:android:da9e7960006e1a378c32db',
    messagingSenderId: '352111075138',
    projectId: 'myprotfolio-a0b51',
    storageBucket: 'myprotfolio-a0b51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwKsQrNh8jeeLHZXwqc1O2nAZpAxTbpCU',
    appId: '1:352111075138:ios:ce78c312439d9fd98c32db',
    messagingSenderId: '352111075138',
    projectId: 'myprotfolio-a0b51',
    storageBucket: 'myprotfolio-a0b51.firebasestorage.app',
    iosBundleId: 'com.example.booking',
  );
}
